[package]
name = "push_through"
version = "0.1.0-dev"
edition = "2021"

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
const_format = "0.2"
env_logger = "0.9"
log = "0.4"
rocket = "0.5.0-rc.1"
serde = { version = "1", features = ["derive"] }
toml = "0.4"
